name: Release

permissions:
  contents: write

on:
  pull_request:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build release
      run: cargo build --release --verbose --target x86_64-unknown-linux-gnu

    - name: Generate a tag
      id: tag
      run: |
        sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml
    
    - name: Create a release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.tag.outputs.version }}
        tag_name: ${{ steps.tag.outputs.version }}
        generate_release_notes: true
        files: target/x86_64-unknown-linux-gnu/release/libbearerauth.so
