name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v**.**.**'

jobs:
  build-and-release:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract tag name
      id: extract_tag
      run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build release
      run: cargo build --release --verbose --target x86_64-unknown-linux-gnu

    - name: Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/x86_64-unknown-linux-gnu/release/libbearerauth.so

    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: Bump version to ${{ steps.extract_tag.outputs.tag }}'
        title: 'chore: Bump version to ${{ steps.extract_tag.outputs.tag }}'
        body: 'This PR was automatically created by the release workflow.'
        branch: develop
        base: main
        draft: false
        delete-branch: false

    - name: Merge PR
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
